'use client'

import { useEffect, useRef, useState } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import { ArrowLeft, Loader2 } from 'lucide-react'
import {
  APBills,
  APBillMatching,
  type APBill,
  type APBillPurchaseOrderOption,
  type APBillGoodsReceiptOption,
  type APBillMatchCheck,
  fmtMoney,
  fmtDate,
} from '@/src/libs/data/AccountingV2Data'
import { SupplierSearchCombobox } from '@/src/components/inventory/SupplierSearchCombobox'

// Scenario 41 — same treatment Scenario 40 gave Expenses (developer
// feedback, 2026-08-31): this used to be a modal, now its own full page,
// matching the reference accounting tool. Same fields/flow as before, just
// its own route now: /accounting/ap-bills/new and /accounting/ap-bills/[id]/edit
// both render this one component, the latter passing billId to load the
// draft first.
export default function BillForm({ billId }: { billId?: string }) {
  const router = useRouter()
  const [initial, setInitial] = useState<APBill | null>(null)
  const [ready, setReady] = useState(!billId)
  const [loadError, setLoadError] = useState<string | null>(null)

  useEffect(() => {
    if (!billId) return
    APBills.get(billId).then((res) => {
      if (res.success && res.data) {
        // Scenario 43 — a fully settled bill is genuinely locked (nothing
        // left to edit), but DRAFT/RECEIVED/PARTIAL/OVERDUE can all still
        // reach this form — how much of it is actually editable is decided
        // below (BillFormFields' isLocked), not gated here.
        if (['PAID', 'CANCELLED'].includes(res.data.status)) {
          setLoadError('This bill is fully settled and can no longer be edited.')
        } else {
          setInitial(res.data)
        }
      } else {
        setLoadError(res.message || res.error || 'Bill not found.')
      }
      setReady(true)
    })
  }, [billId])

  if (!ready) {
    return <div className="px-6 py-8 lg:px-10 text-sm text-gray-400">Loading…</div>
  }
  if (loadError) {
    return (
      <div className="px-6 py-8 lg:px-10">
        <Link
          href="/accounting/ap-bills"
          className="mb-4 inline-flex items-center gap-1.5 text-sm text-gray-500 hover:text-gray-800"
        >
          <ArrowLeft className="h-4 w-4" />
          Back to AP Invoices
        </Link>
        <div className="p-3 bg-red-50 border border-red-200 rounded text-sm text-red-700">
          {loadError}
        </div>
      </div>
    )
  }

  return <BillFormFields initial={initial} onSaved={() => router.push('/accounting/ap-bills')} />
}

function BillFormFields({ initial, onSaved }: { initial: APBill | null; onSaved: () => void }) {
  const [form, setForm] = useState({
    supplierId: initial?.supplierId ?? '',
    purchaseOrderId: initial?.purchaseOrderId ?? '',
    goodsReceiptIds: initial?.goodsReceipts?.map((r) => r.id) ?? ([] as string[]),
    billDate: initial?.billDate?.slice(0, 10) ?? new Date().toISOString().slice(0, 10),
    dueDate:
      initial?.dueDate?.slice(0, 10) ??
      new Date(Date.now() + 30 * 86400000).toISOString().slice(0, 10),
    description: initial?.description ?? '',
    // Scenario 41 — the supplier's own invoice number; never generated by
    // this system. Required to create a bill by hand; may still be blank
    // when editing a DRAFT auto-generated off a receipt, filled in here
    // once the real invoice arrives.
    billNumber: initial?.billNumber ?? '',
    subtotal: String(initial?.subtotal ?? ''),
    taxAmount: String(initial?.taxAmount ?? ''),
    // Left blank on a new bill so the backend auto-calculates it from the
    // supplier's withholding rate; pre-filled here so editing an existing
    // bill shows (and can override) what was actually computed.
    withholdingAmount: initial?.withholdingAmount != null ? String(initial.withholdingAmount) : '',
    sourceOfPayment: initial?.sourceOfPayment ?? '',
    referenceNumber: initial?.referenceNumber ?? '',
    serialNumber: initial?.serialNumber ?? '',
  })
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState<string | null>(null)
  // Scenario 43 — a bill that's left DRAFT (already received/posted to the
  // GL) locks everything except how it's paid. See ap-bills.service.ts's
  // update() for the matching backend guard.
  const isLocked = !!initial && initial.status !== 'DRAFT'
  const [purchaseOrders, setPurchaseOrders] = useState<APBillPurchaseOrderOption[]>([])
  const [receipts, setReceipts] = useState<APBillGoodsReceiptOption[]>([])
  const [matchCheck, setMatchCheck] = useState<APBillMatchCheck | null>(null)
  const supplierIdOnMount = useRef(form.supplierId)

  useEffect(() => {
    if (!form.supplierId) {
      setPurchaseOrders([])
      return
    }
    // Only reset the previously-picked PO when the supplier actually
    // changes after mount — not on the initial load of an existing bill.
    if (form.supplierId !== supplierIdOnMount.current) {
      setForm((f) => ({ ...f, purchaseOrderId: '', goodsReceiptIds: [] }))
    }
    APBillMatching.purchaseOrders(form.supplierId).then((r) =>
      setPurchaseOrders(r.data?.data ?? [])
    )
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [form.supplierId])

  useEffect(() => {
    if (!form.purchaseOrderId) {
      setReceipts([])
      return
    }
    APBillMatching.receipts(form.purchaseOrderId).then((r) => setReceipts(r.data?.data ?? []))
  }, [form.purchaseOrderId])

  useEffect(() => {
    if (!initial?.id || !initial?.purchaseOrderId) return
    APBillMatching.matchCheck(initial.id).then((r) => setMatchCheck(r.data ?? null))
  }, [initial?.id, initial?.purchaseOrderId])

  const toggleReceipt = (id: string) => {
    setForm((f) => ({
      ...f,
      goodsReceiptIds: f.goodsReceiptIds.includes(id)
        ? f.goodsReceiptIds.filter((r) => r !== id)
        : [...f.goodsReceiptIds, id],
    }))
  }

  const submit = async (e: React.FormEvent) => {
    e.preventDefault()
    if (isLocked) {
      // Scenario 43 — only these three fields are still writable once a
      // bill has left DRAFT; sending anything else trips the backend's
      // matching guard, so the payload is deliberately minimal here.
      setSaving(true)
      setError(null)
      const res = await APBills.update(initial!.id, {
        sourceOfPayment: form.sourceOfPayment || undefined,
        referenceNumber: form.referenceNumber || undefined,
        serialNumber: form.serialNumber || undefined,
      })
      setSaving(false)
      if (!res.success) {
        setError(res.message || res.error || 'Save failed')
        return
      }
      onSaved()
      return
    }
    if (!form.supplierId) {
      setError('Supplier is required')
      return
    }
    // Scenario 41 — required to create a bill by hand (matches the backend
    // DTO); editing an existing DRAFT may still leave it blank if it hasn't
    // arrived yet, so this only gates a brand-new bill.
    if (!initial && !form.billNumber.trim()) {
      setError("The supplier's invoice number is required")
      return
    }
    setSaving(true)
    setError(null)
    const payload = {
      ...form,
      purchaseOrderId: form.purchaseOrderId || undefined,
      goodsReceiptIds: form.purchaseOrderId ? form.goodsReceiptIds : undefined,
      billNumber: form.billNumber.trim() || undefined,
      subtotal: Number(form.subtotal),
      taxAmount: Number(form.taxAmount || 0),
      // Omit entirely when blank so the backend auto-calculates from the
      // supplier's withholding rate instead of overriding it with 0.
      withholdingAmount: form.withholdingAmount === '' ? undefined : Number(form.withholdingAmount),
      sourceOfPayment: form.sourceOfPayment || undefined,
      referenceNumber: form.referenceNumber || undefined,
      serialNumber: form.serialNumber || undefined,
    }
    const res = initial ? await APBills.update(initial.id, payload) : await APBills.create(payload)
    setSaving(false)
    if (!res.success) {
      setError(res.message || res.error || 'Save failed')
      return
    }
    onSaved()
  }

  return (
    <div className="px-6 py-8 lg:px-10">
      <Link
        href="/accounting/ap-bills"
        className="mb-4 inline-flex items-center gap-1.5 text-sm text-gray-500 hover:text-gray-800"
      >
        <ArrowLeft className="h-4 w-4" />
        Back to AP Invoices
      </Link>

      <h1 className="text-2xl font-semibold text-prominent-purple-900">
        {initial ? 'Edit Bill' : 'New Bill'}
      </h1>
      <p className="mt-1 text-sm text-gray-500">
        Record a supplier bill. Receiving posts a journal entry to the GL.
      </p>

      <form
        onSubmit={submit}
        className="mt-6 space-y-3 rounded-xl border border-gray-200 bg-white p-5"
      >
        {isLocked ? (
          <div className="space-y-3">
            <div className="rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 text-xs text-amber-700">
              This bill has already been received and posted to the GL — only how it&apos;s paid can
              still be changed below.
            </div>
            <InfoRow label="Supplier" value={initial?.supplier?.name ?? '—'} />
            {initial?.purchaseOrder && (
              <InfoRow label="Purchase Order" value={initial.purchaseOrder.code} />
            )}
            <div className="grid grid-cols-2 gap-3">
              <InfoRow label="Bill Date" value={fmtDate(initial?.billDate)} />
              <InfoRow label="Due Date" value={fmtDate(initial?.dueDate)} />
            </div>
            {initial?.description && <InfoRow label="Description" value={initial.description} />}
            <InfoRow label="SI / Invoice Number" value={initial?.billNumber ?? '—'} />
            <div className="grid grid-cols-2 gap-3">
              <InfoRow label="Subtotal" value={fmtMoney(initial?.subtotal ?? 0)} />
              <InfoRow label="Input Tax (VAT)" value={fmtMoney(initial?.taxAmount ?? 0)} />
            </div>
          </div>
        ) : (
          <>
            <Field label="Supplier *">
              <SupplierSearchCombobox
                value={form.supplierId}
                onChange={(id) => setForm({ ...form, supplierId: id })}
                initialLabel={
                  initial?.supplier
                    ? `${initial.supplier.code} — ${initial.supplier.name}`
                    : undefined
                }
              />
            </Field>
            {form.supplierId && (
              <Field label="Purchase Order (for the 3-way match)">
                <select
                  value={form.purchaseOrderId}
                  onChange={(e) => setForm({ ...form, purchaseOrderId: e.target.value })}
                  className="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg"
                >
                  <option value="">— None —</option>
                  {purchaseOrders.map((po) => (
                    <option key={po.id} value={po.id}>
                      {po.code} — {fmtMoney(po.totalAmount)} ({po.status})
                    </option>
                  ))}
                </select>
              </Field>
            )}
            {form.purchaseOrderId && (
              <Field label="Receiving Reports matched to this bill">
                {receipts.length === 0 ? (
                  <p className="text-xs text-gray-400">
                    No receiving reports posted against this PO yet.
                  </p>
                ) : (
                  <div className="space-y-1 border border-gray-200 rounded-lg p-2 max-h-28 overflow-y-auto">
                    {receipts.map((r) => (
                      <label key={r.id} className="flex items-center gap-2 text-xs">
                        <input
                          type="checkbox"
                          checked={form.goodsReceiptIds.includes(r.id)}
                          onChange={() => toggleReceipt(r.id)}
                        />
                        {r.code} — {fmtDate(r.receivedAt)}
                      </label>
                    ))}
                  </div>
                )}
              </Field>
            )}
            {matchCheck?.applicable && (
              <div
                className={`text-xs px-3 py-2 rounded-lg ${
                  matchCheck.matched
                    ? 'bg-emerald-50 text-emerald-700'
                    : 'bg-amber-50 text-amber-700'
                }`}
              >
                3-way match:{' '}
                <span className="font-semibold">{matchCheck.matched ? 'Matched' : 'Variance'}</span>
                {' — '}PO {fmtMoney(matchCheck.poTotal ?? 0)} · RRs{' '}
                {fmtMoney(matchCheck.rrTotal ?? 0)} · Bill {fmtMoney(matchCheck.invoiceTotal)}
              </div>
            )}
            <div className="grid grid-cols-2 gap-3">
              <Field label="Bill Date *">
                <input
                  required
                  type="date"
                  value={form.billDate}
                  onChange={(e) => setForm({ ...form, billDate: e.target.value })}
                  className="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg"
                />
              </Field>
              <Field label="Due Date *">
                <input
                  required
                  type="date"
                  value={form.dueDate}
                  onChange={(e) => setForm({ ...form, dueDate: e.target.value })}
                  className="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg"
                />
              </Field>
            </div>
            <Field label="Description">
              <input
                value={form.description}
                onChange={(e) => setForm({ ...form, description: e.target.value })}
                className="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg"
              />
            </Field>
            <Field label={initial ? 'SI / Invoice Number' : 'SI / Invoice Number *'}>
              <input
                required={!initial}
                value={form.billNumber}
                onChange={(e) => setForm({ ...form, billNumber: e.target.value })}
                placeholder="The Supplier Invoice (SI) number printed on the supplier's own invoice"
                className="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg"
              />
              {initial && !form.billNumber && (
                <p className="mt-1 text-xs text-amber-600">
                  Required before this bill can be received.
                </p>
              )}
            </Field>
            <div className="grid grid-cols-2 gap-3">
              <Field label="Subtotal *">
                <input
                  required
                  type="number"
                  step="0.01"
                  value={form.subtotal}
                  onChange={(e) => setForm({ ...form, subtotal: e.target.value })}
                  className="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg"
                />
              </Field>
              <Field label="Input Tax (VAT)">
                <input
                  type="number"
                  step="0.01"
                  value={form.taxAmount}
                  onChange={(e) => setForm({ ...form, taxAmount: e.target.value })}
                  className="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg"
                />
              </Field>
            </div>
            <Field label="Withholding Tax">
              <input
                type="number"
                step="0.01"
                value={form.withholdingAmount}
                onChange={(e) => setForm({ ...form, withholdingAmount: e.target.value })}
                placeholder="Auto-calculated from the supplier's withholding rate if left blank"
                className="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg"
              />
            </Field>
          </>
        )}
        {initial && (
          <>
            <div className="pt-1 border-t text-xs font-semibold text-gray-500 uppercase tracking-wide">
              How this bill will be paid
            </div>
            <Field label="Source of Payment">
              <select
                value={form.sourceOfPayment}
                onChange={(e) => setForm({ ...form, sourceOfPayment: e.target.value })}
                className="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg"
              >
                <option value="">— Select —</option>
                <option value="cash">Cash</option>
                <option value="check">Check</option>
                <option value="bank_transfer">Bank Transfer</option>
                <option value="gcash">GCash</option>
                <option value="card">Card</option>
                <option value="other">Other</option>
              </select>
            </Field>
            <Field label="Reference Number">
              <input
                value={form.referenceNumber}
                onChange={(e) => setForm({ ...form, referenceNumber: e.target.value })}
                className="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg"
              />
            </Field>
            {form.sourceOfPayment === 'check' && (
              <Field label="Serial Number (Cheque No.)">
                <input
                  value={form.serialNumber}
                  onChange={(e) => setForm({ ...form, serialNumber: e.target.value })}
                  placeholder="e.g. 0001234"
                  className="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg"
                />
              </Field>
            )}
          </>
        )}
        {error && (
          <div className="p-2 bg-red-50 border border-red-200 rounded text-xs text-red-700">
            {error}
          </div>
        )}
        <div className="flex justify-end gap-2 pt-3 border-t border-zinc-200">
          <Link
            href="/accounting/ap-bills"
            className="rounded-lg px-4 py-2 text-sm font-medium text-zinc-700 hover:bg-zinc-100"
          >
            Cancel
          </Link>
          <button
            type="submit"
            disabled={saving}
            className="flex items-center gap-2 rounded-lg bg-prominent-purple-700 px-4 py-2 text-sm font-semibold text-white hover:bg-prominent-purple-800 disabled:opacity-60"
          >
            {saving && <Loader2 className="h-4 w-4 animate-spin" />}
            {saving ? 'Saving...' : 'Save'}
          </button>
        </div>
      </form>
    </div>
  )
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <label className="block">
      <span className="block text-xs font-medium text-gray-600 mb-1">{label}</span>
      {children}
    </label>
  )
}

// Scenario 43 — read-only counterpart to Field, for a locked bill's fields.
function InfoRow({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <span className="block text-xs font-medium text-gray-600 mb-1">{label}</span>
      <p className="text-sm text-gray-800">{value}</p>
    </div>
  )
}
