export const CRM_PERMISSIONS = {
  LEADS_READ: 'crm:leads:read',
  LEADS_CREATE: 'crm:leads:create',
  LEADS_UPDATE: 'crm:leads:update',
  LEADS_DELETE: 'crm:leads:delete',
  LEADS_CONVERT: 'crm:leads:convert',
  LEADS_ASSIGN: 'crm:leads:assign',
  CUSTOMERS_READ: 'crm:customers:read',
  CUSTOMERS_CREATE: 'crm:customers:create',
  CUSTOMERS_UPDATE: 'crm:customers:update',
  CUSTOMERS_DELETE: 'crm:customers:delete',
  INTERACTIONS_READ: 'crm:interactions:read',
  INTERACTIONS_CREATE: 'crm:interactions:create',
  REMINDERS_READ: 'crm:reminders:read',
  REMINDERS_CREATE: 'crm:reminders:create',
  REMINDERS_UPDATE: 'crm:reminders:update',
  SEGMENTS_READ: 'crm:segments:read',
  SEGMENTS_MANAGE: 'crm:segments:manage',
  COLLECTORS_READ: 'crm:collectors:read',
  COLLECTORS_CREATE: 'crm:collectors:create',
  COLLECTORS_UPDATE: 'crm:collectors:update',
  COLLECTORS_DELETE: 'crm:collectors:delete',
  COLLECTORS_REMIT: 'crm:collectors:remit',
  INSTALLMENT_ACCOUNTS_READ: 'crm:installment-accounts:read',
  INSTALLMENT_ACCOUNTS_CREATE: 'crm:installment-accounts:create',
  INSTALLMENT_ACCOUNTS_UPDATE: 'crm:installment-accounts:update',
  INSTALLMENT_ACCOUNTS_DELETE: 'crm:installment-accounts:delete',
  INSTALLMENT_ACCOUNTS_EARLY_PAYOFF: 'crm:installment-accounts:early_payoff',
  INSTALLMENT_ACCOUNTS_RECORD_PAYMENT: 'crm:installment-accounts:record_payment',
  PIPELINE_READ: 'crm:pipeline:read',
  PIPELINE_MANAGE: 'crm:pipeline:manage',
  SETTINGS_CONFIGURE: 'crm:settings:configure',
  AGENTS_READ: 'crm:agents:read',
  AGENTS_CREATE: 'crm:agents:create',
  AGENTS_UPDATE: 'crm:agents:update',
  AGENTS_DELETE: 'crm:agents:delete',
  INCENTIVES_READ: 'crm:collection-incentives:read',
  INCENTIVES_CREATE: 'crm:collection-incentives:create',
  INCENTIVES_UPDATE: 'crm:collection-incentives:update',
  INCENTIVES_DELETE: 'crm:collection-incentives:delete',
  INCENTIVES_APPROVE: 'crm:collection-incentives:approve',
  WILDCARD: 'crm:*',
} as const

export type CrmPermission = (typeof CRM_PERMISSIONS)[keyof typeof CRM_PERMISSIONS]
