export const HR_PERMISSIONS = {
  EMPLOYEES_READ: 'hr:employees:read',
  EMPLOYEES_CREATE: 'hr:employees:create',
  EMPLOYEES_UPDATE: 'hr:employees:update',
  EMPLOYEES_DELETE: 'hr:employees:delete',
  EMPLOYEES_SELF_READ: 'hr:employees:self:read',
  ATTENDANCE_READ: 'hr:attendance:read',
  ATTENDANCE_UPDATE: 'hr:attendance:update',
  ATTENDANCE_SELF_READ: 'hr:attendance:self:read',
  ATTENDANCE_SELF_LOG: 'hr:attendance:self:log',
  LEAVE_READ: 'hr:leave:read',
  LEAVE_APPROVE: 'hr:leave:approve',
  LEAVE_SELF_REQUEST: 'hr:leave:self:request',
  PAYROLL_READ: 'hr:payroll:read',
  PAYROLL_RUN: 'hr:payroll:run',
  PAYROLL_APPROVE: 'hr:payroll:approve',
  PAYROLL_EXPORT: 'hr:payroll:export',
  PAYSLIPS_READ: 'hr:payslips:read',
  PAYSLIPS_CREATE: 'hr:payslips:create',
  PAYSLIPS_UPDATE: 'hr:payslips:update',
  PAYSLIPS_DELETE: 'hr:payslips:delete',
  SETTINGS_CONFIGURE: 'hr:settings:configure',
  WILDCARD: 'hr:*',
} as const

export const HR_PERMISSION_DESCRIPTIONS: Record<
  (typeof HR_PERMISSIONS)[keyof typeof HR_PERMISSIONS],
  string
> = {
  'hr:employees:read': 'View employee list and profiles',
  'hr:employees:create': 'Onboard new employees',
  'hr:employees:update': 'Edit employee records',
  'hr:employees:delete': 'Offboard or deactivate employees',
  'hr:employees:self:read': 'View own employee profile',
  'hr:attendance:read': 'View timekeeping logs',
  'hr:attendance:update': 'Edit attendance entries',
  'hr:attendance:self:read': 'View own attendance records',
  'hr:attendance:self:log': 'Log own attendance',
  'hr:leave:read': 'View leave requests',
  'hr:leave:approve': 'Approve or reject leave requests',
  'hr:leave:self:request': 'Request leave for self',
  'hr:payroll:read': 'View payroll summaries',
  'hr:payroll:run': 'Process a payroll cutoff',
  'hr:payroll:approve': 'Sign off payroll for release',
  'hr:payroll:export': 'Download payroll reports',
  'hr:payslips:read': 'View employee payslips',
  'hr:payslips:create': 'Create payslips',
  'hr:payslips:update': 'Edit payslip records',
  'hr:payslips:delete': 'Delete payslips',
  'hr:settings:configure': 'Configure pay schedules and leave types',
  'hr:*': 'Wildcard full HR access',
}

export type HrPermission = (typeof HR_PERMISSIONS)[keyof typeof HR_PERMISSIONS]
