export const POS_PERMISSIONS = {
  TERMINALS_READ: 'pos:terminals:read',
  TERMINALS_MANAGE: 'pos:terminals:manage',
  SESSIONS_READ: 'pos:sessions:read',
  SESSIONS_OPEN: 'pos:sessions:open',
  SESSIONS_CLOSE: 'pos:sessions:close',
  TRANSACTIONS_READ: 'pos:transactions:read',
  TRANSACTIONS_CREATE: 'pos:transactions:create',
  TRANSACTIONS_VOID: 'pos:transactions:void',
  TRANSACTIONS_REFUND: 'pos:transactions:refund',
  TRANSACTIONS_AUDIT: 'pos:transactions:audit',
  TRANSACTIONS_OVERRIDE: 'pos:transaction:override',
  TRANSACTIONS_PRICE_OVERRIDE: 'pos:transactions:price_override',
  PROMO_CODES_READ: 'pos:promo-codes:read',
  PROMO_CODES_MANAGE: 'pos:promo-codes:manage',
  GIFT_CARDS_READ: 'pos:gift-cards:read',
  GIFT_CARDS_ISSUE: 'pos:gift-cards:issue',
  GIFT_CARDS_VOID: 'pos:gift-cards:void',
  LOYALTY_READ: 'pos:loyalty:read',
  LOYALTY_TRANSACT: 'pos:loyalty:transact',
  LOYALTY_PROGRAM_READ: 'pos:loyalty-program:read',
  LOYALTY_PROGRAM_MANAGE: 'pos:loyalty-program:manage',
  CASH_DRAWER_READ: 'pos:cash-drawer:read',
  CASH_DRAWER_MANAGE: 'pos:cash-drawer:manage',
  CASHIER_PIN_VERIFY: 'pos:cashier-pin:verify',
  CONFIG_READ: 'pos:config:read',
  CONFIG_MANAGE: 'pos:config:manage',
  CUSTOMERS_READ: 'pos:customers:read',
  CUSTOMERS_CREATE: 'pos:customers:create',
  BRANCH_PRICING_READ: 'pos:branch-pricing:read',
  BRANCH_PRICING_MANAGE: 'pos:branch-pricing:manage',
  FINANCING_TERMS_READ: 'pos:financing-terms:read',
  FINANCING_TERMS_MANAGE: 'pos:financing-terms:manage',
  TPF_PROVIDERS_READ: 'pos:tpf-providers:read',
  TPF_PROVIDERS_MANAGE: 'pos:tpf-providers:manage',
  CASH_IN_TRANSIT_READ: 'pos:cash-in-transit:read',
  CASH_IN_TRANSIT_MANAGE: 'pos:cash-in-transit:manage',
  // No matching Permission row currently seeded in the live DB — flagged as
  // a backend seed-data gap, not a frontend bug. Kept as-is (matches the
  // string the backend controller's @RequirePermissions decorator
  // requires) rather than invented, so it starts working the moment the
  // row is seeded instead of silently drifting from the backend.
  COLLECTIONS_MANAGE: 'pos:collections:manage',
  SERVICE_DRAFTS_CREATE: 'pos:service-drafts:create',
  SERVICE_DRAFTS_READ: 'pos:service-drafts:read',
  SERVICE_DRAFTS_UPDATE: 'pos:service-drafts:update',
  SERVICE_DRAFTS_CANCEL: 'pos:service-drafts:cancel',
  SERVICE_DRAFTS_SOURCE: 'pos:service-drafts:source',
  SERVICE_DRAFTS_INSTALL: 'pos:service-drafts:install',
  SERVICE_DRAFTS_COMPLETE: 'pos:service-drafts:complete',
  WILDCARD: 'pos:*',
} as const

export const POS_PERMISSION_DESCRIPTIONS: Record<
  (typeof POS_PERMISSIONS)[keyof typeof POS_PERMISSIONS],
  string
> = {
  'pos:terminals:read': 'View POS terminals',
  'pos:terminals:manage': 'Create, edit, and delete POS terminals',
  'pos:sessions:read': 'View POS sessions',
  'pos:sessions:open': 'Open a POS session',
  'pos:sessions:close': 'Close a POS session',
  'pos:transactions:read': 'View POS transactions',
  'pos:transactions:create': 'Process POS sales',
  'pos:transactions:void': 'Void a transaction',
  'pos:transactions:refund': 'Process refunds',
  'pos:transactions:audit': 'View POS data-integrity reports (e.g. sales missing a COGS posting)',
  'pos:transaction:override':
    'Approve manager overrides: high-value discounts, receiptless returns, and void transactions',
  'pos:transactions:price_override':
    'Approve a manual price override at checkout — no matching price-list entry, or adjusting the resolved price',
  'pos:promo-codes:read': 'View promo codes',
  'pos:promo-codes:manage': 'Create, edit, and delete promo codes',
  'pos:gift-cards:read': 'View gift cards',
  'pos:gift-cards:issue': 'Issue a new gift card',
  'pos:gift-cards:void': 'Void a gift card',
  'pos:loyalty:read': 'View member loyalty accounts',
  'pos:loyalty:transact': 'Earn and redeem loyalty points at checkout',
  'pos:loyalty-program:read': 'View loyalty program rules',
  'pos:loyalty-program:manage': 'Create and edit loyalty program rules',
  'pos:cash-drawer:read': 'View cash drawer events',
  'pos:cash-drawer:manage': 'Record cash drawer events',
  'pos:cashier-pin:verify':
    'Identify another user (cashier or manager) by PIN — cashier switch and checkout override authorization',
  'pos:config:read': 'View POS configuration',
  'pos:config:manage': 'Manage POS configuration',
  'pos:customers:read': 'Search POS customers by phone',
  'pos:customers:create': 'Create a walk-in customer from the POS terminal',
  'pos:branch-pricing:read': 'View branch price overrides',
  'pos:branch-pricing:manage': 'Create and edit branch price overrides',
  'pos:financing-terms:read': 'View installment financing terms',
  'pos:financing-terms:manage': 'Create and edit installment financing terms',
  'pos:tpf-providers:read': 'View TPF (third-party financing) providers',
  'pos:tpf-providers:manage': 'Create and edit TPF (third-party financing) providers',
  'pos:cash-in-transit:read': 'View outstanding Cash-in-Transit sessions',
  'pos:cash-in-transit:manage': 'Clear Cash-in-Transit sessions into a bank deposit',
  'pos:collections:manage':
    "Collect payments against a customer's existing installment dues at POS",
  'pos:service-drafts:create': 'Open a new service job / materials estimate',
  'pos:service-drafts:read': 'View service jobs / materials estimates',
  'pos:service-drafts:update': 'Edit a draft service job / materials estimate',
  'pos:service-drafts:cancel': 'Cancel a service job',
  'pos:service-drafts:source':
    'Check on-hand stock for a service job and raise a Purchase Request for any shortfall',
  'pos:service-drafts:install':
    'Start the install step on a service job (assign a technician) and record actual materials used',
  'pos:service-drafts:complete':
    'Complete a service job: deduct actual materials used from stock and close the job',
  'pos:*': 'Wildcard full POS access',
}

export type PosPermission = (typeof POS_PERMISSIONS)[keyof typeof POS_PERMISSIONS]
