export const SALES_PERMISSIONS = {
  CUSTOMERS_READ: 'sales:customers:read',
  CUSTOMERS_CREATE: 'sales:customers:create',
  CUSTOMERS_UPDATE: 'sales:customers:update',
  CUSTOMERS_DELETE: 'sales:customers:delete',
  QUOTATIONS_READ: 'sales:quotations:read',
  QUOTATIONS_CREATE: 'sales:quotations:create',
  QUOTATIONS_UPDATE: 'sales:quotations:update',
  QUOTATIONS_SEND: 'sales:quotations:send',
  QUOTATIONS_APPROVE: 'sales:quotations:approve',
  ORDERS_READ: 'sales:orders:read',
  ORDERS_CREATE: 'sales:orders:create',
  ORDERS_UPDATE: 'sales:orders:update',
  ORDERS_APPROVE: 'sales:orders:approve',
  ORDERS_CANCEL: 'sales:orders:cancel',
  DELIVERIES_READ: 'sales:deliveries:read',
  DELIVERIES_CREATE: 'sales:deliveries:create',
  DELIVERIES_UPDATE: 'sales:deliveries:update',
  INVOICES_READ: 'sales:invoices:read',
  INVOICES_CREATE: 'sales:invoices:create',
  INVOICES_UPDATE: 'sales:invoices:update',
  RETURNS_READ: 'sales:returns:read',
  RETURNS_CREATE: 'sales:returns:create',
  RETURNS_APPROVE: 'sales:returns:approve',
  REPORTS_READ: 'sales:reports:read',
  WILDCARD: 'sales:*',
} as const

export type SalesPermission = (typeof SALES_PERMISSIONS)[keyof typeof SALES_PERMISSIONS]
